name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      throttr:
        image: ghcr.io/throttr/throttr:2.1.0-release
        ports:
          - 9000:9000
        options: >-
          --health-cmd "bash -c 'echo > /dev/tcp/localhost/9000'" 
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug

      - name: Validate Composer
        run: composer validate --strict

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
